//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVM
{
    public partial class NoteWork
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string TextNote { get; set; }
        public string DataStart { get; set; }
        public string DataEnd { get; set; }
        public bool IsDone { get; set; }
        public int ColorID { get; set; }
    }
}